#ifndef CONFIG_H_
#define CONFIG_H_

// uncomment this if you want to handshake with a aiortc
// #define CONFIG_DTLS_USE_ECDSA 1

#define SCTP_MTU (1200)
#define CONFIG_MTU (1300)

#ifndef CONFIG_USE_LWIP
#define CONFIG_USE_LWIP 0
#endif

#ifndef CONFIG_MBEDTLS_DEBUG
#define CONFIG_MBEDTLS_DEBUG 0
#endif

#ifndef CONFIG_MBEDTLS_2_X
#define CONFIG_MBEDTLS_2_X 0
#endif

#if CONFIG_MBEDTLS_2_X
#define RSA_KEY_LENGTH 512
#else
#define RSA_KEY_LENGTH 1024
#endif

#ifndef CONFIG_DTLS_USE_ECDSA
#define CONFIG_DTLS_USE_ECDSA 0
#endif

#ifndef CONFIG_USE_USRSCTP
#define CONFIG_USE_USRSCTP 1
#endif

#ifndef CONFIG_VIDEO_BUFFER_SIZE
#define CONFIG_VIDEO_BUFFER_SIZE (CONFIG_MTU * CONFIG_LIBPEER_VIDEO_BUFFER_SIZE_MTUS)
#endif

#ifndef CONFIG_AUDIO_BUFFER_SIZE
#define CONFIG_AUDIO_BUFFER_SIZE (CONFIG_MTU * CONFIG_LIBPEER_AUDIO_BUFFER_SIZE_MTUS)
#endif

#ifndef CONFIG_DATA_BUFFER_SIZE
#define CONFIG_DATA_BUFFER_SIZE (SCTP_MTU * CONFIG_LIBPEER_DATA_BUFFER_SIZE_MTUS)
#endif

#ifndef CONFIG_SDP_BUFFER_SIZE
#define CONFIG_SDP_BUFFER_SIZE 8096
#endif

#ifndef CONFIG_MQTT_BUFFER_SIZE
#define CONFIG_MQTT_BUFFER_SIZE 4096
#endif

#ifndef CONFIG_HTTP_BUFFER_SIZE
#define CONFIG_HTTP_BUFFER_SIZE 4096
#endif

#ifndef CONFIG_TLS_READ_TIMEOUT
#define CONFIG_TLS_READ_TIMEOUT 3000
#endif

#define AUDIO_LATENCY CONFIG_LIBPEER_AUDIO_LATENCY_MS
#define KEEPALIVE_CONNCHECK CONFIG_LIBPEER_KEEPALIVE_CONNCHECK
#define CONFIG_IPV6 0
// empty will use first active interface
#define CONFIG_IFACE_PREFIX ""

#ifdef CONFIG_LIBPEER_LOG_LEVEL_ERROR
#define LOG_LEVEL LEVEL_ERROR
#endif // CONFIG_LIBPEER_LOG_LEVEL_ERROR
#ifdef CONFIG_LIBPEER_LOG_LEVEL_WARN
#define LOG_LEVEL LEVEL_WARN
#endif // CONFIG_LIBPEER_LOG_LEVEL_WARN
#ifdef CONFIG_LIBPEER_LOG_LEVEL_INFO
#define LOG_LEVEL LEVEL_INFO
#endif // CONFIG_LIBPEER_LOG_LEVEL_INFO
#ifdef CONFIG_LIBPEER_LOG_LEVEL_DEBUG
#define LOG_LEVEL LEVEL_DEBUG
#endif // CONFIG_LIBPEER_LOG_LEVEL_DEBUG

// #define LOG_LEVEL LEVEL_DEBUG
#define LOG_REDIRECT 0

// Disable MQTT and HTTP signaling
// #define DISABLE_PEER_SIGNALING 1

#endif  // CONFIG_H_
